[package]
name = "rust-chain"
version = "0.1.0"
authors = ["Nolan  <braman.n@northeastern.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
